// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUp8Ijv8aQek1eJsyuAQHZR2LF5NQTpoc',
    appId: '1:647134464282:android:494357285d112e729b04a3',
    messagingSenderId: '647134464282',
    projectId: 'contactfirestore-18748',
    storageBucket: 'contactfirestore-18748.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1jo7ulrBMfxuf9OUS8YupF7cYtgVfRUY',
    appId: '1:647134464282:ios:4bc1a59f442279f89b04a3',
    messagingSenderId: '647134464282',
    projectId: 'contactfirestore-18748',
    storageBucket: 'contactfirestore-18748.appspot.com',
    iosBundleId: 'com.example.contactfirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYchKBKUsJZO2zp1JROdo0Bv2MBeKmY1U',
    appId: '1:647134464282:web:93e60ab96d235f039b04a3',
    messagingSenderId: '647134464282',
    projectId: 'contactfirestore-18748',
    authDomain: 'contactfirestore-18748.firebaseapp.com',
    storageBucket: 'contactfirestore-18748.appspot.com',
    measurementId: 'G-KPGRDD3QVS',
  );
}
